version: '3'

services:
  vue-frontend:
    build:
      context: ./vue-frontend
      dockerfile: dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - sagawa-network

  bun-api:
    build:
      context: ./bun-api
      dockerfile: dockerfile
    restart: always
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=production
      # Add your environment variables here
    volumes:
      - ./bun-api/uploads:/app/uploads
    networks:
      - sagawa-network

networks:
  sagawa-network:
    driver: bridge

server {
    listen 80;
    server_name yourdomain.com www.yourdomain.com;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    
    location /api {
        proxy_pass http://bun-api:9999;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    location ~ /.well-known/acme-challenge {
        allow all;
        root /var/www/certbot;
    }
}