services:
  frontend:
    build: ./vue-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./bun-api
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=https://a1971aa5-5930-4854-82ef-747bd405cc0a-us-east-2.apps.astra.datastax.com
    restart: always
