name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install frontend dependencies
      working-directory: ./vue-frontend
      run: bun install

    - name: Run frontend tests
      working-directory: ./vue-frontend
      run: |
        bun run test:unit || echo "No tests configured"
        bun run lint || echo "No linting configured"

    - name: Build frontend
      working-directory: ./vue-frontend
      run: bun run build

    - name: Upload frontend build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: vue-frontend/dist/

  test-api:
    name: Test API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install API dependencies
      working-directory: ./bun-api
      run: bun install

    - name: Run API tests
      working-directory: ./bun-api
      run: |
        bun test || echo "No tests configured"

    - name: Type check
      working-directory: ./bun-api
      run: |
        bun run type-check || echo "No type checking configured"

  build-production:
    name: Build Production
    needs: [test-frontend, test-api]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Run production build script
      run: |
        chmod +x ./production-build.sh
        ./production-build.sh --frontend-only

    - name: Upload production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: /tmp/sagawagroup-build/